version: 2
updates:
    # Enable version updates for npm
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 10
      assignees:
          - "resham57"
      reviewers:
          - "resham57"
      labels:
          - "dependencies"
      commit-message:
          prefix: "chore(deps)"
          include: "scope"

    # Enable version updates for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 10
      assignees:
          - "resham57"
      reviewers:
          - "resham57"
      labels:
          - "dependencies(Actions)"
      commit-message:
          prefix: "chore(deps-actions)"
          include: "scope"
